// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApzQXHnomPP_02v4bjMGgQmcgYfF1vRWw',
    appId: '1:936079041005:web:8542f31c50c6ae77ba07e4',
    messagingSenderId: '936079041005',
    projectId: 'dtdcparcel',
    authDomain: 'dtdcparcel.firebaseapp.com',
    storageBucket: 'dtdcparcel.appspot.com',
    measurementId: 'G-YQPC029ZM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9EMQ5oxLJsnodOOvqWxMhgRc_Ubk7Lw',
    appId: '1:936079041005:android:6777602187be7896ba07e4',
    messagingSenderId: '936079041005',
    projectId: 'dtdcparcel',
    storageBucket: 'dtdcparcel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7SvQH5VVfWM9Js6rXRYv09NT6UrxKlTA',
    appId: '1:936079041005:ios:a69d5a5fc6ce2becba07e4',
    messagingSenderId: '936079041005',
    projectId: 'dtdcparcel',
    storageBucket: 'dtdcparcel.appspot.com',
    iosClientId: '936079041005-qh0f06b01a3e0d1t0r87mhrgcoq585d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickMyParcelCustomer',
  );
}
